namespace Line.Messaging.Webhooks
{
    /// <summary>
    /// Line Beacon
    /// </summary>
    public class Beacon
    {
        /// <summary>
        /// Hardware ID of the beacon that was detected
        /// </summary>
        public string Hwid { get; }

        /// <summary>
        /// Type of beacon event
        /// </summary>
        public BeaconType Type { get; }

        /// <summary>
        /// Optional. Device message of beacon that was detected
        /// The "device message" consists of data generated by the beacon to send notifications to bots. The beacon.dm property is only included in webhooks from devices that support the "device message" property. You can use beacon.dm with the LINE Simple Beacon specification. For more information, see the LINE Simple Beacon specification.
        /// </summary>
        public string Dm { get; }

        public Beacon(string hwid, BeaconType type, string dm)
        {
            Hwid = hwid;
            Type = type;
            Dm = dm;
        }
    }
}
